server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huashuohair?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall  #配置扩展插件，常用的插件有=>stat:监控统计  wall:防御sql注入
      initialSize: 5 #初始化连接大小
      minIdle: 5 #最小连接池数量
      maxActive: 20 #最大连接池数量
      maxWait: 60000  #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL    #测试连接
      testWhileIdle: true  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxOpenPreparedStatements: 20
  thymeleaf:
    #开启thymeleaf视图解析
    enabled: true  
    #编码
    encoding: utf-8  
    #前缀
    prefix: classpath:/templates/ 
    #是否使用缓存
    cache: false  
    #严格的HTML语法模式
    mode: HTML  
    #后缀名
    suffix: .html  
    
# 配置mybatis规则
mybatis:
  #sql映射文件位置
  mapper-locations: classpath:mapper/*.xml  
  #configuration:
    #map-underscore-to-camel-case: true
#springdoc
springdoc:
  swagger-ui:
    enabled: true 
  packagesToScan: com.huashuohair.app.controller    
